### ISSUE TITLE
Is development still active here? How do I contribute?

### ISSUE THREAD

**Issue by kanhirun** [metricfu/Saikuro#8]
Hey metricfu,

I have a PR I would like to contribute, and possibly a few more down the road. How do I contribute?

Cheers,
Kel

**Comment by bf4** [comment]
@kanhirun I'm not actively working on Saikuro, but you are welcome to contribute and perhaps even maintain it, if you wish.  There's an open PR #1 that I never finished reviewing.  As an aside, have you seen [Fukuzatsu](https://gitlab.com/coraline/fukuzatsu) ?

**Comment by kanhirun** [comment]
@bf4 Thanks for letting me know. 👍  I am trying out Fukuzatsu right now, and it seems to fit what I'm looking for.
